# ############################################################################
# Model: S4-T
# Authors: Luca Della Libera 2023
# ############################################################################

# Adapted from:
# https://github.com/speechbrain/speechbrain/blob/v0.5.15/recipes/LibriSpeech/ASR/transducer/hparams/conformer_transducer.yaml

experiment_name: LibriSpeech/S4-T

# Seed needs to be set at top of YAML
seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
train_splits: [train-clean-100]
dev_splits: [dev-clean]
test_splits: [test-clean, test-other]
train_csv: !ref <save_folder>/train.csv
valid_csv: !ref <save_folder>/dev-clean.csv
test_csv:
  - !ref <save_folder>/test-clean.csv
  - !ref <save_folder>/test-other.csv
skip_prep: False

# Output directories
output_folder: !ref results/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save

# Preprocessing parameters
avoid_if_longer_than: 60.0
sample_rate: 16000
sorting: ascending
n_fft: 512
n_mels: 80
win_length: 32

# Training parameters
num_epochs: 100
#num_ctc_epochs: 60
#ctc_weight: 0.47
#num_ce_epochs: 60
#ce_weight: 0.47

grad_accumulation_factor: 4
dynamic_batching: True
train_batch_size: 8
valid_batch_size: 8
test_batch_size: 4
train_max_batch_length: 80
valid_max_batch_length: 80
test_max_batch_length: 60
num_buckets: 80
max_batch_size: 128
dataloader_workers: 6

vocab_size: 1000  # If token_type=char, must be set equal to the number of found characters
token_type: unigram  # ["unigram", "bpe", "char"]
character_coverage: 1.0
pad_index: 0
bos_index: 1
eos_index: 2
blank_index: 3

lr: 0.002
weight_decay: 0.01
warmup_steps: 10000

nonfinite_patience: 10
max_grad_norm: 5.0
auto_mix_prec: False
ckpt_interval_minutes: 600

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.1
d_model: 256
num_encoder_layers: 12
d_ffn: 2048
kernel_size: 31
causal: False
padding: same
s4_layer_type: !name:models.layers.gss.GSS
s4_layer_kwargs:
    gating_size: 256
    hidden_size: 256
    state_size: 128

#embedding_dim: 128
decoder_neurons: 512
decoder_num_layers: 1

joint_dim: 640

# Decoding parameters
valid_search_freq: 5
beam_size: 4
# state_beam and expand_beam set according to https://arxiv.org/abs/1904.02619
state_beam: 2.3
expand_beam: 2.3

# Options
pretrain: True
augment: True
keep_checkpoints: 10

# Modules
feature_extractor: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>
    win_length: !ref <win_length>

normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    update_until_epoch: 4

augmentation: !new:speechbrain.lobes.augment.SpecAugment
    time_warp: True
    time_warp_window: 5
    time_warp_mode: bicubic
    freq_mask: True
    n_freq_mask: 2
    time_mask: True
    n_time_mask: 2
    replace_with_zero: False
    freq_mask_width: 30
    time_mask_width: 20

speed_perturb: !new:speechbrain.processing.speech_augmentation.SpeedPerturb
    orig_freq: !ref <sample_rate>
    speeds: [95, 100, 105]

frontend: !new:speechbrain.lobes.models.convolution.ConvolutionFrontEnd
    input_shape: [null, null, !ref <n_mels>]
    num_blocks: 2
    num_layers_per_block: 1
    out_channels: (128, 128)
    kernel_sizes: (3, 3)
    strides: (2, 2)
    residuals: (False, False)
    padding: !ref <padding>

encoder: !new:models.s4.S4
    input_size: 2560
    d_model: !ref <d_model>
    num_encoder_layers: !ref <num_encoder_layers>
    d_ffn: !ref <d_ffn>
    dropout: !ref <dropout>
    activation: !ref <activation>
    kernel_size: !ref <kernel_size>
    causal: !ref <causal>
    s4_layer_type: !ref <s4_layer_type>
    s4_layer_kwargs: !ref <s4_layer_kwargs>

encoder_proj: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <d_model>
    n_neurons: !ref <joint_dim>
    bias: False

#encoder_head: !new:speechbrain.nnet.linear.Linear
#    input_size: !ref <joint_dim>
#    n_neurons: !ref <vocab_size>

embedding: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <vocab_size>
    #embedding_dim: !ref <embedding_dim>
    consider_as_one_hot: True
    blank_id: !ref <blank_index>

decoder: !new:speechbrain.nnet.RNN.LSTM
    input_shape: [null, null, !ref <vocab_size> - 1]
    hidden_size: !ref <decoder_neurons>
    num_layers: !ref <decoder_num_layers>
    re_init: True

decoder_proj: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <decoder_neurons>
    n_neurons: !ref <joint_dim>
    bias: False

#decoder_head: !new:speechbrain.nnet.linear.Linear
#    input_size: !ref <joint_dim>
#    n_neurons: !ref <vocab_size>

joiner: !new:speechbrain.nnet.transducer.transducer_joint.Transducer_joint
    joint: sum  # [sum | concat]
    nonlinearity: !ref <activation>

transducer_head: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <joint_dim>
    n_neurons: !ref <vocab_size>
    bias: False

modules:
    feature_extractor: !ref <feature_extractor>
    normalizer: !ref <normalizer>
    augmentation: !ref <augmentation>
    speed_perturb: !ref <speed_perturb>
    frontend: !ref <frontend>
    encoder: !ref <encoder>
    encoder_proj: !ref <encoder_proj>
    #encoder_head: !ref <encoder_head>
    embedding: !ref <embedding>
    decoder: !ref <decoder>
    decoder_proj: !ref <decoder_proj>
    #decoder_head: !ref <decoder_head>
    joiner: !ref <joiner>
    transducer_head: !ref <transducer_head>

model: !new:torch.nn.ModuleList
    [[!ref <feature_extractor>, !ref <normalizer>, !ref <augmentation>, !ref <speed_perturb>,
      !ref <frontend>, !ref <encoder>, !ref <encoder_proj>, #!ref <encoder_head>,
      !ref <embedding>, !ref <decoder>, !ref <decoder_proj>, #!ref <decoder_head>,
      !ref <joiner>, !ref <transducer_head>]]

# Loss functions
transducer_loss: !name:speechbrain.nnet.losses.transducer_loss
    use_torchaudio: True
    blank_index: !ref <blank_index>

# ctc_loss: !name:speechbrain.nnet.losses.ctc_loss
#    blank_index: !ref <blank_index>

#ce_loss: !name:speechbrain.nnet.losses.nll_loss
#    label_smoothing: 0.1

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 1.e-8
    weight_decay: !ref <weight_decay>

lr_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
   lr_initial: !ref <lr>
   n_warmup_steps: !ref <warmup_steps>

# Searchers
greedy_searcher: !new:speechbrain.decoders.transducer.TransducerBeamSearcher
    decode_network_lst: [!ref <embedding>, !ref <decoder>, !ref <decoder_proj>]
    tjoint: !ref <joiner>
    classifier_network: [!ref <transducer_head>]
    blank_id: !ref <blank_index>
    beam_size: 1
    nbest: 1

beam_searcher: !new:speechbrain.decoders.transducer.TransducerBeamSearcher
    decode_network_lst: [!ref <embedding>, !ref <decoder>, !ref <decoder_proj>]
    tjoint: !ref <joiner>
    classifier_network: [!ref <transducer_head>]
    blank_id: !ref <blank_index>
    beam_size: !ref <beam_size>
    nbest: 1
    state_beam: !ref <state_beam>
    expand_beam: !ref <expand_beam>

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt

# Pretrainer
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
    paths:
